### ISSUE TITLE
Monk dll missing 

### ISSUE THREAD

**Issue by Volk1911** [Holic75/SolastaMonk#1]
When I try to load Monk - I get this error 

[SolastaMonkClass] Version '0.1.0'. Loading.
[SolastaMonkClass] [Error] File 'C:\Program Files (x86)\Steam\steamapps\common\Slasta_COTM\Mods\SolastaMonkClass\SolastaMonkClass.dll' not found.
[SolastaMonkClass] Loading time 0.00 s.

Thank you

**Comment by Holic75** [comment]
The mod is not yet released. If you want to use it you should compile it yourself.
