### ISSUE TITLE
Flurry of Blows is not restricted to unarmed strikes

### ISSUE THREAD

**Issue by Similacrest** [Holic75/SolastaMonk#3]
Solasta version 1.1.11_Final, tested with a minimal setup of Solasta Monk 1.0.3 + SolastaModAPI 1.1.0+ Mod Helpers 0.9.3.

After making the Attack action and activating Flurry of Blows, if a non-monk weapon is held, Flurry of Blows allows to make attacks with that weapon (tested on an elf character) instead of unarmed strikes. This even works with ranged weapons, and can activate Open Hand Technique. 

Another related issue is that it's impossible to make an unarmed strike when dual wielding (unlike the tabletop, where it can be kicks, headbutts, etc.), which indeed prevents the flurry from working when dual wielding monk weapons. If this is a technical limitation as I suspect, it should probably be documented it the feature description.

Not sure where to locate a save game, let me know if you need it. UMM log should also be irrelevant.

**Comment by Holic75** [comment]
fixed
